In [ ]:
!pip install tensorflow_text

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 60.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 KB 37.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 103.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 81.4 MB/s eta 0:00:00
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 1.12
    Uninstalling flatbuffers-1.12:
      Successfully uninstalled flatbuffers-1.12
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.9.0
    Uninstalling tensorflow-estimator-2.9.0:
      Successfully uninstalled tensorflow-estimator-2.9.0
  Attempting uninstall: keras
    Found existing installation: keras 2.9.0
    Uninstalling keras-2.9.0:
      Successfully 

In [ ]:
import tensorflow_hub as hub
import tensorflow_text as text

In [ ]:
preprocess_url='https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
encoder_url='https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'

In [ ]:
bert_preprocess_model=hub.KerasLayer(preprocess_url)



In [ ]:
text_test=['nice movie indeed','i  love python programming']
preprocessed_text=bert_preprocess_model(text_test)
# print(preprocessed_text)
preprocessed_text.keys()



dict_keys(['input_word_ids', 'input_type_ids', 'input_mask'])

In [ ]:
preprocessed_text['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [ ]:
preprocessed_text['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [ ]:
bert_model=hub.KerasLayer(encoder_url)
bert_result= bert_model(preprocessed_text)


In [ ]:
bert_result.keys()

dict_keys(['sequence_output', 'pooled_output', 'default', 'encoder_outputs'])

In [ ]:
bert_result['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917738 , -0.214119  ,  0.4976956 , ...,  0.24465248,
        -0.4733446 ,  0.8175866 ],
       [-0.91712326, -0.47935176, -0.7865696 , ..., -0.6175175 ,
        -0.7102685 ,  0.92184305]], dtype=float32)>

In [ ]:
bert_result['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292067,  0.08567822,  0.14476836, ..., -0.09677087,
          0.08722129,  0.07711094],
        [ 0.17839354, -0.19006018,  0.50349367, ..., -0.05869842,
          0.3271711 , -0.15578555],
        [ 0.18701491, -0.43388742, -0.4887515 , ..., -0.15502787,
          0.00145216, -0.24470924],
        ...,
        [ 0.12083021,  0.12884282,  0.4645354 , ...,  0.07375491,
          0.1744193 ,  0.16522156],
        [ 0.07967912, -0.01190624,  0.5022538 , ...,  0.13777728,
          0.21002221,  0.00624587],
        [-0.07212694, -0.28303483,  0.59033346, ...,  0.47551912,
          0.1666846 , -0.08920337]],

       [[-0.07900582,  0.36335114, -0.21101543, ..., -0.17183763,
          0.16299734,  0.6724271 ],
        [ 0.27883524,  0.4371634 , -0.3576478 , ..., -0.04463633,
          0.3831516 ,  0.58879817],
        [ 1.2037672 ,  1.0727024 ,  0.48408753, ...,  0.24920942,
          0.40730953,  0.40481883],
        ...,

In [ ]:
bert_result['encoder_outputs'][-1]==bert_result['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>

In [ ]:
bert_result['encoder_outputs'][10]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-2.1951795e-02,  2.1303640e-01,  3.1135854e-01, ...,
         -2.3917958e-01, -2.7870795e-01,  2.0408517e-01],
        [ 8.3098364e-01,  1.9078255e-01,  7.1134472e-01, ...,
         -3.0024439e-01,  3.1152457e-01, -2.5934008e-01],
        [ 3.7308952e-01, -4.2212594e-01, -6.6690952e-01, ...,
         -4.5297647e-01,  3.2045287e-01, -2.9988611e-01],
        ...,
        [ 3.3166349e-01,  7.1835887e-01,  8.9961064e-01, ...,
         -3.4914568e-01, -2.9987028e-01,  5.2388936e-01],
        [ 2.3853350e-01,  2.0484520e-01,  1.1306415e+00, ...,
         -1.5113032e-01, -1.3781080e-01,  7.6999351e-02],
        [-3.8412127e-01, -3.8158771e-01,  1.3397276e+00, ...,
          5.7755494e-01, -1.5540022e-01, -2.9294536e-01]],

       [[ 1.4363037e-01,  1.6980167e-01,  4.5119956e-02, ...,
         -6.2168323e-02, -1.5753128e-02,  2.8787017e-01],
        [ 5.8476055e-01,  2.6993316e-01, -2.8520727e-01, ...,
          3.3893099e-01,  1.

##TEXT-Classification using BERT

In [ ]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [ ]:
import pandas as pd
df=pd.read_csv("/content/spam.csv",encoding="ISO-8859-1")
df.head(5)

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [ ]:
df.groupby('v1').describe()

v2                                                                 \
     count unique                                                top freq   
v1                                                                          
ham   4825   4516                             Sorry, I'll call later   30   
spam   747    653  Please call our customer service representativ...    4   

     Unnamed: 2                                                            \
          count unique                                                top   
v1                                                                          
ham          45     39   bt not his girlfrnd... G o o d n i g h t . . .@"   
spam          5      4                                        PO Box 5249   

          Unnamed: 3                                    Unnamed: 4         \
     freq      count unique                    top freq      count unique   
v1                                                                          
ham     3         10      9                     GE    2          6      5   
spam    2          2      1   MK17 92H. 450Ppw 16"    2          0      0   

                    
          top freq  
v1                  
ham   GNT:-)"    2  
spam      NaN  NaN

In [ ]:
df['v1'].value_counts()

ham     4825
spam     747
Name: v1, dtype: int64

In [ ]:
df_spam=df[df['v1']=="spam"]
# print(df_spam)
df_spam.shape


(747, 5)

In [ ]:
df_ham=df[df['v1']=="ham"]
print(df_ham)
df_ham.shape


       v1                                                 v2 Unnamed: 2  \
0     ham  Go until jurong point, crazy.. Available only ...        NaN   
1     ham                      Ok lar... Joking wif u oni...        NaN   
3     ham  U dun say so early hor... U c already then say...        NaN   
4     ham  Nah I don't think he goes to usf, he lives aro...        NaN   
6     ham  Even my brother is not like to speak with me. ...        NaN   
...   ...                                                ...        ...   
5565  ham                                       Huh y lei...        NaN   
5568  ham              Will Ì_ b going to esplanade fr home?        NaN   
5569  ham  Pity, * was in mood for that. So...any other s...        NaN   
5570  ham  The guy did some bitching but I acted like i'd...        NaN   
5571  ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
3           

(4825, 5)

In [ ]:
df_ham_downsampled=df_ham.sample(df_spam.shape[0])
df_ham_downsampled.shape

(747, 5)

In [ ]:
df_balanced=pd.concat([df_spam,df_ham_downsampled])
df_balanced.shape

(1494, 5)

In [ ]:
df_balanced['v1'].value_counts()

spam    747
ham     747
Name: v1, dtype: int64

In [ ]:
df_balanced['spam']=df_balanced['v1'].apply(lambda x: 1 if x=='spam' else 0)
df_balanced.sample(10)

v1                                                 v2 Unnamed: 2  \
1339   ham          Every monday..nxt week vl be completing..        NaN   
2127   ham  Tessy..pls do me a favor. Pls convey my birthd...        NaN   
1894  spam  FreeMsg Hey U, i just got 1 of these video/pic...        NaN   
258   spam  We tried to contact you re your reply to our o...        NaN   
2586   ham  If you don't respond imma assume you're still ...        NaN   
374   spam  Thanks for your Ringtone Order, Reference T91....        NaN   
2412  spam  I don't know u and u don't know me. Send CHAT ...        NaN   
4067  spam  TBS/PERSOLVO. been chasing us since Sept forå£...        NaN   
4521   ham                         DO U WANT 2 MEET UP 2MORRO        NaN   
126    ham  Just so that you know,yetunde hasn't sent mone...        NaN   

     Unnamed: 3 Unnamed: 4  spam  
1339        NaN        NaN     0  
2127        NaN        NaN     0  
1894        NaN        NaN     1  
258         NaN        NaN     1  
2586        NaN        NaN     0  
374         NaN        NaN     1  
2412        NaN        NaN     1  
4067        NaN        NaN     1  
4521        NaN        NaN     0  
126         NaN        NaN     0

In [ ]:
from sklearn.model_selection import train_test_split
(X_train, X_test, y_train, y_test) = train_test_split(df_balanced['v2'],df_balanced['spam'],stratify=df_balanced['spam'])

In [ ]:
X_train.head(4)

5231    I realise you are a busy guy and i'm trying no...
3673    You have won a Nokia 7250i. This is what you g...
3947    I like to think there's always the possibility...
2219    You have WON a guaranteed å£1000 cash or a å£2...
Name: v2, dtype: object

In [ ]:
preprocess_url='https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
encoder_url='https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'

In [ ]:
bert_preprocess_model=hub.KerasLayer(preprocess_url)
bert_encoder=hub.KerasLayer(encoder_url)

In [ ]:
def get_sentences(sentences):
  preprocessed_text_2=bert_preprocess_model(sentences)
  return bert_encoder(preprocessed_text_2)['pooled_output']

get_sentences([
    "500$ discount.harry up",
    "bhavin are you up for vollyball match tomorrow ?"
])  

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79626   , -0.4449325 , -0.8482474 , ..., -0.5802873 ,
        -0.675496  ,  0.8861206 ],
       [-0.85225606, -0.3150407 , -0.6833537 , ..., -0.49616683,
        -0.5873189 ,  0.87876636]], dtype=float32)>

#Bert Layer

In [ ]:
text_input=tf.keras.layers.Input(shape=(), dtype=tf.string, name="text")
preprocessed_text_2=bert_preprocess_model(text_input)
outputs=bert_encoder(preprocessed_text_2)

l=tf.keras.layers.Dropout(0.1, name='dropout')(outputs['pooled_output'])
l=tf.keras.layers.Dense(1,activation='sigmoid',name='output')(l)

model=tf.keras.Model(inputs=[text_input],outputs=[l])
model.summary()

Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 text (InputLayer)              [(None,)]            0           []                               
                                                                                                  
 keras_layer_2 (KerasLayer)     {'input_type_ids':   0           ['text[0][0]']                   
                                (None, 128),                                                      
                                 'input_mask': (Non                                               
                                e, 128),                                                          
                                 'input_word_ids':                                                
                                (None, 128)}                                                  

In [ ]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy']
              )

In [ ]:
model.fit(X_train,y_train,epochs=5)

Epoch 1/5
35/35 [==============================] - 23s 323ms/step - loss: 0.7045 - accuracy: 0.5277
Epoch 2/5
35/35 [==============================] - 12s 335ms/step - loss: 0.5538 - accuracy: 0.7643
Epoch 3/5
35/35 [==============================] - 12s 343ms/step - loss: 0.4728 - accuracy: 0.8339
Epoch 4/5
35/35 [==============================] - 12s 344ms/step - loss: 0.4178 - accuracy: 0.8554
Epoch 5/5
35/35 [==============================] - 12s 344ms/step - loss: 0.3869 - accuracy: 0.8527


In [ ]:
model.evaluate(X_test,y_test)

12/12 [==============================] - 6s 346ms/step - loss: 0.3301 - accuracy: 0.9171


[0.33012959361076355, 0.9171122908592224]

In [ ]:
emails=['Control who sees what Connections may see your profile, posts, and activities Edit preferences',
'Stay up to date See posts and career updates from your connections, or directly message them for free',
'Once your invitation is accepted, you will be connected with another member']

In [ ]:
model.predict(emails)
#if the value is < 0.5 than email is not spam
# else spam


1/1 [==============================] - 1s 885ms/step


array([[0.6864874 ],
       [0.41646984],
       [0.48111007]], dtype=float32)